// src/app/api/settings/ai-template/reset/route.ts
// API endpoint to reset AI template to defaults

import { NextRequest, NextResponse } from "next/server";
import { auth } from "@clerk/nextjs/server";
import { db } from "@/lib/prisma";
import { TASK_TYPES } from "@/types/task";

export const dynamic = "force-dynamic";

/**
 * Get default AI tasks based on the current implementation
 */
function getDefaultAITasks() {
  return [
    {
      title: "Escrow Opened",
      description: "Escrow should be opened within 1 business day of acceptance",
      taskTypes: [TASK_TYPES.ESCROW],
      dueDateType: "days_after_acceptance" as const,
      dueDateValue: 1,
    },
    {
      title: "Initial Deposit Due",
      description: "Submit initial earnest money deposit",
      taskTypes: [TASK_TYPES.ESCROW],
      dueDateType: "days_after_acceptance" as const,
      dueDateValue: 3, // Default to 3 days if not specified in timeline
    },
    {
      title: "Inspection Contingency",
      description: "Complete inspections and remove inspection contingency",
      taskTypes: [TASK_TYPES.TIMELINE],
      dueDateType: "days_after_acceptance" as const,
      dueDateValue: 17, // Default California standard
    },
    {
      title: "Appraisal Contingency",
      description: "Complete appraisal and remove appraisal contingency",
      taskTypes: [TASK_TYPES.LENDER],
      dueDateType: "days_after_acceptance" as const,
      dueDateValue: 17,
    },
    {
      title: "Loan Contingency",
      description: "Secure loan approval and remove loan contingency",
      taskTypes: [TASK_TYPES.LENDER],
      dueDateType: "days_after_acceptance" as const,
      dueDateValue: 21,
    },
    {
      title: "Broker file approved",
      description: "Broker file should be approved at least 7 days before closing",
      taskTypes: [TASK_TYPES.BROKER],
      dueDateType: "days_from_close" as const,
      dueDateValue: -7, // 7 days before close
    },
  ];
}

/**
 * Reset the AI template to default tasks
 */
export async function POST(request: NextRequest) {
  try {
    const { userId: clerkId } = await auth();
    if (!clerkId) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const user = await db.user.findUnique({
      where: { clerkId },
      select: { id: true },
    });

    if (!user) {
      return NextResponse.json({ error: "User not found" }, { status: 404 });
    }

    const userId = user.id;
    const defaultTasks = getDefaultAITasks();

    // Check if user already has an AI template
    const existingTemplate = await db.userTaskTemplate.findFirst({
      where: {
        userId,
        isAiGenerated: true,
      },
    });

    let template;
    if (existingTemplate) {
      // Update existing template with defaults
      template = await db.userTaskTemplate.update({
        where: { id: existingTemplate.id },
        data: {
          name: "AI Generated Tasks",
          description: "Smart default tasks automatically generated by AI based on timeline events",
          fileType: "escrow",
          isDefaultForNewFiles: true,
          tasks: defaultTasks,
        },
      });
    } else {
      // Create new template with defaults
      template = await db.userTaskTemplate.create({
        data: {
          userId,
          name: "AI Generated Tasks",
          description: "Smart default tasks automatically generated by AI based on timeline events",
          fileType: "escrow",
          isDefaultForNewFiles: true,
          isAiGenerated: true,
          tasks: defaultTasks,
        },
      });
    }

    return NextResponse.json({ template }, { status: 200 });
  } catch (error) {
    console.error("Error resetting AI template:", error);
    return NextResponse.json(
      { error: "Failed to reset AI template" },
      { status: 500 }
    );
  }
}
