-- AlterTable
ALTER TABLE "parses" ADD COLUMN     "brokers" JSONB,
ADD COLUMN     "buyerNames" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "classificationCache" JSONB,
ADD COLUMN     "closingCosts" JSONB,
ADD COLUMN     "closingDate" TEXT,
ADD COLUMN     "contingencies" JSONB,
ADD COLUMN     "earnestMoneyAmount" DOUBLE PRECISION,
ADD COLUMN     "earnestMoneyDeposit" JSONB,
ADD COLUMN     "earnestMoneyHolder" TEXT,
ADD COLUMN     "effectiveDate" TEXT,
ADD COLUMN     "escrowHolder" TEXT,
ADD COLUMN     "extractionDetails" JSONB,
ADD COLUMN     "financing" JSONB,
ADD COLUMN     "initialDepositDueDate" TEXT,
ADD COLUMN     "isAllCash" BOOLEAN,
ADD COLUMN     "loanType" TEXT,
ADD COLUMN     "personalPropertyIncluded" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "propertyAddress" TEXT,
ADD COLUMN     "purchasePrice" DOUBLE PRECISION,
ADD COLUMN     "sellerDeliveryOfDisclosuresDate" TEXT,
ADD COLUMN     "sellerNames" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "timelineEvents" JSONB,
ADD COLUMN     "transactionType" TEXT DEFAULT 'escrow',
ALTER COLUMN "status" SET DEFAULT 'PENDING';
